// Generated by tools/generate_script_abi.py. Do not edit.
using System.Numerics;
using System.Runtime.InteropServices;
namespace Tartarus;
public static class ScriptAbi { public const int Version = 3; }
[StructLayout(LayoutKind.Sequential)]
public struct ProjectCall {
    public nint Operation;
    public nint Data;
    public int Size;
}
[StructLayout(LayoutKind.Sequential)]
public struct EntityFrame {
    public float Dt;
    public uint Entity;
    public uint Script;
    public int Phase;
    public int Enabled;
    public nint ClassName;
    public nint Fields;
}
[StructLayout(LayoutKind.Sequential)]
public struct NativeRequest {
    public Vector3 A;
    public Vector3 B;
    public Vector3 C;
    public float Value;
    public uint Entity;
    public uint Script;
    public int Result;
    public nint Text;
}
