// Generated by tools/generate_game_frames.py. Project adapter ABI, not engine SDK.
using System.Numerics;
using System.Runtime.InteropServices;
namespace Tartarus.Gameplay;
[StructLayout(LayoutKind.Sequential)]
public unsafe struct PlayerFrame {
    public float Dt;
    public float Yaw;
    public float Pitch;
    public float MoveX;
    public float MoveY;
    public float LookPitch;
    public float LookYaw;
    public float SizeX;
    public float SizeY;
    public float EyeHeight;
    public float MoveSpeed;
    public float SprintMultiplier;
    public float JumpSpeed;
    public float Gravity;
    public float MouseSensitivity;
    public float StickLookDegPerSec;
    public float KillY;
    public float RootMotionWeight;
    public float MaxYawRate;
    public float YawFreeCenter;
    public float YawFreeRange;
    public float CrouchHeight;
    public float CrouchSpeedMultiplier;
    public float JumpBufferTime;
    public float CoyoteTime;
    public float GroundAccelTime;
    public float GroundDecelTime;
    public float AirAccelTime;
    public float SinceGrounded;
    public float JumpBuffer;
    public float CrouchBlend;
    public float CrouchBlendRate;
    public float YawDropped;
    public Vector3 Position;
    public Vector3 Velocity;
    public Vector3 RespawnFeet;
    public Vector3 RootMotionVelocity;
    public Vector3 WishVelocity;
    public int ReadInput;
    public int Sprint;
    public int JumpDown;
    public int Crouch;
    public int AimHeld;
    public int Grounded;
    public int Crouched;
    public int Jumped;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct WeaponFrame {
    public float Dt;
    public float Rpm;
    public float CycleDelay;
    public float HoldSeconds;
    public float RegripMin;
    public float RegripMax;
    public float Cooldown;
    public float CycleWait;
    public float IdleTime;
    public float RegripDelay;
    public float SinceShot;
    public float SinceUnhidden;
    public float ReloadHeldSeconds;
    public float Random;
    public int Operation;
    public int Ammo;
    public int Magazine;
    public int BurstRounds;
    public int AllowFullAuto;
    public int PerRound;
    public int CycleAfterShot;
    public int HipProcedural;
    public int RecoilProfile;
    public int UnityRecoil;
    public int Equipped;
    public int Chambered;
    public int CycleSeen;
    public int StopReload;
    public int FullAuto;
    public int BurstRemaining;
    public int WaitingShot;
    public int Tags;
    public int InTransition;
    public int WallBlocked;
    public int Pressed;
    public int Held;
    public int ReloadWasDown;
    public int ReloadHoldFired;
    public int Events;
    public int Commands;
    public int Result;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ShotFrame {
    public Vector3 Origin;
    public Vector3 Direction;
    public float Spread;
    public float ImpactImpulse;
    public float ImpactMaxSpeed;
    public float BulletHoleRadius;
    public float Range;
    public int Pellets;
    public int RandomSeed;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcCoverFrame {
    public Vector3 Pos;
    public Vector3 Normal;
    public Vector3 PeekLeft;
    public Vector3 PeekRight;
    public float LastUsed;
    private int _High; public bool High {get=>_High!=0;set=>_High=value?1:0;}
    private int _Peek0; public bool Peek0 {get=>_Peek0!=0;set=>_Peek0=value?1:0;}
    private int _Peek1; public bool Peek1 {get=>_Peek1!=0;set=>_Peek1=value?1:0;}
    public int ClaimedBy;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcMateFrame {
    public Vector3 Feet;
    private int _Dead; public bool Dead {get=>_Dead!=0;set=>_Dead=value?1:0;}
    public int Index;
    public int Squad;
    public int Doing;
    public int Cover;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcIntentFrame {
    public Vector3 MoveTarget;
    public Vector3 AimPoint;
    public Vector3 LookPoint;
    public float Lean;
    public float Cower;
    private int _Move; public bool Move {get=>_Move!=0;set=>_Move=value?1:0;}
    private int _Crouch; public bool Crouch {get=>_Crouch!=0;set=>_Crouch=value?1:0;}
    private int _Aim; public bool Aim {get=>_Aim!=0;set=>_Aim=value?1:0;}
    private int _FaceAim; public bool FaceAim {get=>_FaceAim!=0;set=>_FaceAim=value?1:0;}
    private int _Fire; public bool Fire {get=>_Fire!=0;set=>_Fire=value?1:0;}
    private int _Suppress; public bool Suppress {get=>_Suppress!=0;set=>_Suppress=value?1:0;}
    private int _Reload; public bool Reload {get=>_Reload!=0;set=>_Reload=value?1:0;}
    private int _BlindFire; public bool BlindFire {get=>_BlindFire!=0;set=>_BlindFire=value?1:0;}
    public int Pace;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcServiceFrame {
    public Vector3 A;
    public Vector3 B;
    public Vector3 C;
    public float Value;
    public int Operation;
    public int Index;
    public int Count;
    public int Result;
    public nint Data;
    public NpcCoverFrame Cover;
    public NpcMateFrame Mate;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcBrainFrame {
    public float Now;
    public float Ammo01;
    public float PlayerHeight;
    public float MemoryAwareness;
    public float MemoryLastSeen;
    public float MemoryUncertainty;
    public float DoingSince;
    public float BoundWaitFrom;
    public float PhaseStart;
    public float PhaseUntil;
    public float NoCoverUntil;
    public float IdleUntil;
    public float BlockedTime;
    public float LastOwnSight;
    public float LastHurt;
    public float Suppression;
    public float CoverFireOrder;
    public float PinnedSince;
    public float LastBlindFire;
    public float Skill;
    public float MeleeAt;
    public float CowerUntil;
    public float GlanceUntil;
    public float CoverCheckAt;
    public float SquadCoverFireUntil;
    public float SquadCoverRequestAt;
    public float SquadPushUntil;
    public float SquadFlankDoneAt;
    public float SquadPincerDoneAt;
    public Vector3 Feet;
    public Vector3 Eye;
    public Vector3 Goal;
    public Vector3 PostPos;
    public Vector3 GlanceAt;
    public Vector3 Threat;
    public Vector3 PlayerFeet;
    public Vector3 SeenPoint;
    private int _Known; public bool Known {get=>_Known!=0;set=>_Known=value?1:0;}
    private int _Visible; public bool Visible {get=>_Visible!=0;set=>_Visible=value?1:0;}
    private int _Shotgun; public bool Shotgun {get=>_Shotgun!=0;set=>_Shotgun=value?1:0;}
    private int _Reloading; public bool Reloading {get=>_Reloading!=0;set=>_Reloading=value?1:0;}
    private int _Retreated; public bool Retreated {get=>_Retreated!=0;set=>_Retreated=value?1:0;}
    private int _CoverGood; public bool CoverGood {get=>_CoverGood!=0;set=>_CoverGood=value?1:0;}
    private int _HasFlankToken; public bool HasFlankToken {get=>_HasFlankToken!=0;set=>_HasFlankToken=value?1:0;}
    private int _HasPushToken; public bool HasPushToken {get=>_HasPushToken!=0;set=>_HasPushToken=value?1:0;}
    public int Operation;
    public int TargetBehaviour;
    public int Doing;
    public int Phase;
    public int ShotsAtPhase;
    public int ShotsFired;
    public int SearchStep;
    public int Squad;
    public int Index;
    public int Cover;
    public int Role;
    public int PeekSide;
    public int EmptyPeeks;
    public int VisiblePoints;
    public int SquadCount;
    public int MateCount;
    public int CoverCount;
    public int SquadPushHolder;
    public int SquadFlankHolder;
    public int SquadPincerHolder;
    public int SquadCoverRequest;
    public int DeathCount;
    public int Result;
    public int SearchCoverCalled;
    public int Bounds;
    public int CoveredBounds;
    public int Backpedals;
    public int BlindFires;
    public int Flanks;
    public int FlankFails;
    public int Pincers;
    public nint Services;
    public nint Context;
    public Vector3* Deaths;
    public float* DeathTimes;
    public NpcIntentFrame Intent;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VitalsFrame {
    public float MaxHealth;
    public float RegenDelay;
    public float RegenRate;
    public float RespawnDelay;
    public float SpawnProtection;
    public float Health;
    public float SinceHit;
    public float DeadTime;
    public float Protection;
    public float DamageTaken;
    public float HurtFlash;
    public float Hitmarker;
    public float Dt;
    public float Amount;
    public float Taken;
    public float Health01;
    public float RespawnProgress;
    public float DeathFade;
    public float DeathDrop;
    public float DeathRoll;
    public float EyeHeight;
    public float CameraYaw;
    public int Operation;
    public int GodMode;
    public int Dead;
    public int JustDied;
    public int DiedThisTick;
    public int Deaths;
    public int HitmarkerKill;
    public int HitmarkerHead;
    public int Indicators;
    public int WantsRespawn;
    public Vector3 Source;
    public fixed float SourceX[8];
    public fixed float SourceY[8];
    public fixed float SourceZ[8];
    public fixed float Age[8];
    public fixed float Strength[8];
    public fixed float ArcAngle[8];
    public fixed float ArcAlpha[8];
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct DamageFrame {
    public float Distance;
    public float Start;
    public float End;
    public float MinScale;
    public float Damage;
    public float HeadMultiplier;
    public float LimbMultiplier;
    public float HitY;
    public float FootY;
    public float Height;
    public float Yaw;
    public float Result;
    public int Operation;
    public int Zone;
    public int Region;
    public int Part;
    public Vector3 Camera;
    public Vector3 Source;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct GravityFrame {
    public float Dt;
    public float Yaw;
    public float Scroll;
    public float GrabRange;
    public float AssistRange;
    public float AssistConeDeg;
    public float ScrollTurnDeg;
    public float MinThrowSpeed;
    public float MaxThrowSpeed;
    public float ChargeTime;
    public float Backspin;
    public float HoldDistance;
    public float Charge;
    public float HoldYaw;
    public float RotationW;
    public float PredictSpeed;
    public int Operation;
    public int Left;
    public int Right;
    public int Alt;
    public int Control;
    public int LeftPrev;
    public int RightPrev;
    public int Charging;
    public int HaveHoldPoint;
    public int Handle;
    public int Held;
    public Vector3 Eye;
    public Vector3 Forward;
    public Vector3 CameraRight;
    public Vector3 PrevHoldPoint;
    public Vector3 HoldVelocity;
    public Vector3 Rotation;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct AiRuleFrame {
    public float Distance;
    public float Angle;
    public float Speed;
    public float Suppression;
    public float Alertness;
    public float Focal;
    public float Peripheral;
    public float Range;
    public float BaseRate;
    public float Dt;
    public float Now;
    public float Rate;
    public float Awareness;
    public float LastSeen;
    public float LastHeard;
    public float Uncertainty;
    public float TimeOnTarget;
    public float SelfSpeed;
    public float Skill;
    public float Difficulty;
    public float VisibleFraction;
    public float Random;
    public float Waited;
    public float MaxWait;
    public float PinnedFor;
    public float SinceSeen;
    public float Facing;
    public float SinceStrike;
    public float Reach;
    public float Cooldown;
    public float Radius;
    public float Memory;
    public float M;
    public float K;
    public float B;
    public float C;
    public float Result;
    public int Operation;
    public int VisiblePoints;
    public int Crouched;
    public int Firing;
    public int Known;
    public int Visible;
    public int BecameKnown;
    public int OutsideView;
    public int Flinching;
    public int Weapon;
    public int Exposed;
    public int CoverFire;
    public int KnowsThreat;
    public int CurveKind;
    public int Count;
    public Vector3 Position;
    public Vector3 Velocity;
    public Vector3 Listener;
    public Vector3 Source;
    public float* Values;
    public float* Times;
    public Vector3* Positions;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct AiChoiceFrame {
    public float Now;
    public float LastSeen;
    public float LastHeard;
    public float Health;
    public float MaxHealth;
    public float Suppression;
    public float LastHurt;
    public float Awareness;
    public float Morale;
    public float Distance;
    public float DistanceToCover;
    public float CoverCheckAt;
    public float LastOwnSight;
    public float NoCoverUntil;
    public float PlayerStill;
    public float PlayerUnseen;
    public float LimpUntil;
    public float DoingSince;
    public float NextThink;
    public float Random;
    public int Operation;
    public int Known;
    public int Visible;
    public int Wounded;
    public int Doing;
    public int Phase;
    public int Role;
    public int Shotgun;
    public int Cover;
    public int CoverGood;
    public int HasFlank;
    public int HasPush;
    public int Retreated;
    public int Best;
    public int NeedsCoverCheck;
    public int CoverSearchBlocked;
    public int Change;
    public int Delay;
    public fixed float Scores[11];
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcDamageFrame {
    public float Now;
    public float Amount;
    public float Health;
    public float MaxHealth;
    public float LastHurt;
    public float Suppression;
    public float TimeOnTarget;
    public float Awareness;
    public float LastSeen;
    public float Uncertainty;
    public float ReactionLeft;
    public float LimpUntil;
    public float StaggerUntil;
    public float NextThink;
    public float LimpTime;
    public float HeavyHitDamage;
    public float StaggerTime;
    public float WoundChance;
    public float Random;
    public float Shove;
    public int Operation;
    public int UseHealth;
    public int Entity;
    public int Dead;
    public int Wounded;
    public int Attacker;
    public int Zone;
    public int Part;
    public int Hits;
    public int Known;
    public int Visible;
    public int WoundRolled;
    public int Dummy;
    public int Ignore;
    public int Kill;
    public int Flinch;
    public int NeedRandom;
    public int BecomeWounded;
    public int CallWounded;
    public Vector3 Direction;
    public Vector3 LastHurtFrom;
    public Vector3 LastKnown;
    public Vector3 PlayerFeet;
    public Vector3 PushVelocity;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcHudFrame {
    public Vector3 Feet;
    public float Health;
    public float Awareness;
    public float Suppression;
    private int _Dead; public bool Dead {get=>_Dead!=0;set=>_Dead=value?1:0;}
    private int _Known; public bool Known {get=>_Known!=0;set=>_Known=value?1:0;}
    private int _Visible; public bool Visible {get=>_Visible!=0;set=>_Visible=value?1:0;}
    private int _Crouched; public bool Crouched {get=>_Crouched!=0;set=>_Crouched=value?1:0;}
    private int _Attack; public bool Attack {get=>_Attack!=0;set=>_Attack=value?1:0;}
    private int _Flank; public bool Flank {get=>_Flank!=0;set=>_Flank=value?1:0;}
    private int _Push; public bool Push {get=>_Push!=0;set=>_Push=value?1:0;}
    public int Behaviour;
    public int Role;
    public nint Name;
    public nint Why;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct CombatHudFrame {
    public Vector3 Camera;
    public float Now;
    public float RealTime;
    public float CameraYaw;
    public float FeedLife;
    public float StreakWindow;
    private int _Head; public bool Head {get=>_Head!=0;set=>_Head=value?1:0;}
    private int _PlayerDead; public bool PlayerDead {get=>_PlayerDead!=0;set=>_PlayerDead=value?1:0;}
    private int _Armed; public bool Armed {get=>_Armed!=0;set=>_Armed=value?1:0;}
    private int _Reloading; public bool Reloading {get=>_Reloading!=0;set=>_Reloading=value?1:0;}
    private int _God; public bool God {get=>_God!=0;set=>_God=value?1:0;}
    private int _InfiniteAmmo; public bool InfiniteAmmo {get=>_InfiniteAmmo!=0;set=>_InfiniteAmmo=value?1:0;}
    private int _AiOverlay; public bool AiOverlay {get=>_AiOverlay!=0;set=>_AiOverlay=value?1:0;}
    public int Operation;
    public int Unit;
    public int Ammo;
    public int Magazine;
    public int NpcCount;
    public int DebugFloatCount;
    public int Kills;
    public int Rows;
    public int Streak;
    public int Result;
    public nint FireMode;
    public nint Npcs;
    public nint DebugLines;
    public fixed float ViewProjection[16];
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcMemoryFrame {
    private int _Known; public bool Known {get=>_Known!=0;set=>_Known=value?1:0;}
    private int _Visible; public bool Visible {get=>_Visible!=0;set=>_Visible=value?1:0;}
    public float Awareness;
    public float LastSeen;
    public float LastHeard;
    public float Uncertainty;
    public Vector3 LastKnown;
    public Vector3 LastVelocity;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcPlayerFrame {
    private int _Valid; public bool Valid {get=>_Valid!=0;set=>_Valid=value?1:0;}
    private int _Crouched; public bool Crouched {get=>_Crouched!=0;set=>_Crouched=value?1:0;}
    private int _Dead; public bool Dead {get=>_Dead!=0;set=>_Dead=value?1:0;}
    private int _Fired; public bool Fired {get=>_Fired!=0;set=>_Fired=value?1:0;}
    private int _Reloading; public bool Reloading {get=>_Reloading!=0;set=>_Reloading=value?1:0;}
    private int _Sprinting; public bool Sprinting {get=>_Sprinting!=0;set=>_Sprinting=value?1:0;}
    public float Height;
    public float Radius;
    public float Health;
    public Vector3 Eye;
    public Vector3 Feet;
    public Vector3 Velocity;
    public Vector3 Forward;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcNoiseFrame {
    public Vector3 Position;
    public float Radius;
    public float Loudness;
    public float Time;
    public int Source;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcPerceptionMateFrame {
    private int _Exists; public bool Exists {get=>_Exists!=0;set=>_Exists=value?1:0;}
    public int Squad;
    public NpcMemoryFrame Memory;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcPerceptionFrame {
    public NpcMemoryFrame Memory;
    public NpcPlayerFrame Player;
    public Vector3 Eye;
    public Vector3 SightEye;
    public Vector3 SeenPoint;
    public float Now;
    public float Dt;
    public float Suppression;
    public float ReactionLeft;
    public float PinnedSince;
    public float Skill;
    public float Difficulty;
    public float AimYaw;
    public float AimPitch;
    public float LookYaw;
    public float LookPitch;
    public float NextLook;
    public float LastOwnSight;
    public float CowerUntil;
    public float TimeOnTarget;
    private int _Aim; public bool Aim {get=>_Aim!=0;set=>_Aim=value?1:0;}
    private int _FirstShot; public bool FirstShot {get=>_FirstShot!=0;set=>_FirstShot=value?1:0;}
    public int NoiseCount;
    public int MateCount;
    public int Index;
    public int Squad;
    public int Doing;
    public int VisiblePoints;
    public int Calls;
    public int Startles;
    public nint Noises;
    public nint Mates;
    public nint Services;
    public nint Context;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcSquadMemberFrame {
    public NpcMemoryFrame Memory;
    public Vector3 Feet;
    public Vector3 SightEye;
    public float Health;
    public float MaxHealth;
    public float Skill;
    public float ReactionLeft;
    public float CoverFireOrder;
    private int _Exists; public bool Exists {get=>_Exists!=0;set=>_Exists=value?1:0;}
    private int _Dead; public bool Dead {get=>_Dead!=0;set=>_Dead=value?1:0;}
    private int _Wounded; public bool Wounded {get=>_Wounded!=0;set=>_Wounded=value?1:0;}
    private int _Shotgun; public bool Shotgun {get=>_Shotgun!=0;set=>_Shotgun=value?1:0;}
    private int _Fire; public bool Fire {get=>_Fire!=0;set=>_Fire=value?1:0;}
    private int _Suppress; public bool Suppress {get=>_Suppress!=0;set=>_Suppress=value?1:0;}
    private int _TriggerHeld; public bool TriggerHeld {get=>_TriggerHeld!=0;set=>_TriggerHeld=value?1:0;}
    private int _Reloading; public bool Reloading {get=>_Reloading!=0;set=>_Reloading=value?1:0;}
    private int _EmptyWeapon; public bool EmptyWeapon {get=>_EmptyWeapon!=0;set=>_EmptyWeapon=value?1:0;}
    private int _HasFlank; public bool HasFlank {get=>_HasFlank!=0;set=>_HasFlank=value?1:0;}
    private int _HasPush; public bool HasPush {get=>_HasPush!=0;set=>_HasPush=value?1:0;}
    private int _HasAttack; public bool HasAttack {get=>_HasAttack!=0;set=>_HasAttack=value?1:0;}
    private int _CallCovering; public bool CallCovering {get=>_CallCovering!=0;set=>_CallCovering=value?1:0;}
    public int Role;
    public int Doing;
    public int Cover;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcSquadFrame {
    public NpcMemoryFrame Shared;
    public NpcPlayerFrame Player;
    public float Now;
    public float Difficulty;
    public float SharedAt;
    public float PlayerReloadingSeen;
    public float PushUntil;
    public float NextRoles;
    public float LastDeath;
    public float FlankDoneAt;
    public float PincerDoneAt;
    public float PlayerHurtPushAt;
    public float CoverRequestAt;
    public float CoverFireUntil;
    public float NextTokens;
    public int TotalCount;
    public int MemberCount;
    public int FlankHolder;
    public int PincerHolder;
    public int PushHolder;
    public int CoverRequest;
    public int CoverFirer;
    public int HurtPushes;
    public int CoverOrders;
    public int AttackerCount;
    public fixed int Attackers[4];
    public nint Members;
    public nint MemberIds;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcCombatFrame {
    public NpcPlayerFrame Player;
    public NpcIntentFrame Intent;
    public Vector3 Eye;
    public Vector3 Feet;
    public Vector3 Velocity;
    public Vector3 GunVelocity;
    public Vector3 DamagePoint;
    public Vector3 DamageDirection;
    public float Now;
    public float Dt;
    public float Skill;
    public float Difficulty;
    public float MeleeAt;
    public float MeleeTime;
    public float MeleeHitTime;
    public float MeleeDamage;
    public float BodyYaw;
    public float LookYaw;
    public float LookPitch;
    public float AimYaw;
    public float AimPitch;
    public float AimYawRate;
    public float AimPitchRate;
    public float TimeOnTarget;
    public float Error;
    public float ReactionLeft;
    public float BlockedTime;
    public float BurstPause;
    public float LastShot;
    public float Damage;
    private int _Reloading; public bool Reloading {get=>_Reloading!=0;set=>_Reloading=value?1:0;}
    private int _Pumping; public bool Pumping {get=>_Pumping!=0;set=>_Pumping=value?1:0;}
    private int _AimGun; public bool AimGun {get=>_AimGun!=0;set=>_AimGun=value?1:0;}
    private int _Visible; public bool Visible {get=>_Visible!=0;set=>_Visible=value?1:0;}
    private int _Known; public bool Known {get=>_Known!=0;set=>_Known=value?1:0;}
    private int _HoldFire; public bool HoldFire {get=>_HoldFire!=0;set=>_HoldFire=value?1:0;}
    private int _Dummy; public bool Dummy {get=>_Dummy!=0;set=>_Dummy=value?1:0;}
    private int _Wounded; public bool Wounded {get=>_Wounded!=0;set=>_Wounded=value?1:0;}
    private int _HasAttackToken; public bool HasAttackToken {get=>_HasAttackToken!=0;set=>_HasAttackToken=value?1:0;}
    private int _Signalling; public bool Signalling {get=>_Signalling!=0;set=>_Signalling=value?1:0;}
    private int _Equipped; public bool Equipped {get=>_Equipped!=0;set=>_Equipped=value?1:0;}
    private int _Shotgun; public bool Shotgun {get=>_Shotgun!=0;set=>_Shotgun=value?1:0;}
    private int _TriggerHeld; public bool TriggerHeld {get=>_TriggerHeld!=0;set=>_TriggerHeld=value?1:0;}
    private int _Chambered; public bool Chambered {get=>_Chambered!=0;set=>_Chambered=value?1:0;}
    private int _FirstShot; public bool FirstShot {get=>_FirstShot!=0;set=>_FirstShot=value?1:0;}
    private int _FullAutoSet; public bool FullAutoSet {get=>_FullAutoSet!=0;set=>_FullAutoSet=value?1:0;}
    private int _AllowFullAuto; public bool AllowFullAuto {get=>_AllowFullAuto!=0;set=>_AllowFullAuto=value?1:0;}
    private int _IsFullAuto; public bool IsFullAuto {get=>_IsFullAuto!=0;set=>_IsFullAuto=value?1:0;}
    private int _MeleeLanded; public bool MeleeLanded {get=>_MeleeLanded!=0;set=>_MeleeLanded=value?1:0;}
    private int _Pressed; public bool Pressed {get=>_Pressed!=0;set=>_Pressed=value?1:0;}
    private int _Held; public bool Held {get=>_Held!=0;set=>_Held=value?1:0;}
    private int _Reload; public bool Reload {get=>_Reload!=0;set=>_Reload=value?1:0;}
    private int _ToggleAuto; public bool ToggleAuto {get=>_ToggleAuto!=0;set=>_ToggleAuto=value?1:0;}
    private int _GunNoise; public bool GunNoise {get=>_GunNoise!=0;set=>_GunNoise=value?1:0;}
    private int _Sprinting; public bool Sprinting {get=>_Sprinting!=0;set=>_Sprinting=value?1:0;}
    private int _CallMelee; public bool CallMelee {get=>_CallMelee!=0;set=>_CallMelee=value?1:0;}
    private int _WeaponActive; public bool WeaponActive {get=>_WeaponActive!=0;set=>_WeaponActive=value?1:0;}
    public int Operation;
    public int Ammo;
    public int AmmoSeen;
    public int ShotsFired;
    public int BurstLeft;
    public int Melees;
    public int MeleeHits;
    public int WeaponStateLength;
    public nint Services;
    public nint Context;
    public nint WeaponState;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct AudioShotFrame {
    public double Now;
    public double LastShot;
    public double LastTail;
    public float PitchMin;
    public float PitchMax;
    public float Random;
    public float Distance;
    public float Volume;
    public float PlayerGain;
    public float TailMinInterval;
    public float TailDuckPerVoice;
    public float BurstGap;
    public float Pitch;
    private int _At2D; public bool At2D {get=>_At2D!=0;set=>_At2D=value?1:0;}
    public int Count;
    public int TailVoices;
    public fixed int Player2D[5];
    public fixed int Every[5];
    public fixed int Play[5];
    public fixed float Near[5];
    public fixed float Far[5];
    public fixed float NearWeight[5];
    public fixed float FarWeight[5];
    public fixed float Gain[5];
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct FoleyFrame {
    public float SprintStride;
    public float WalkStride;
    public float StepStrideScale;
    public float CrouchStrideScale;
    public float FallSpeed;
    public float LandMinSpeed;
    public float LandFullSpeed;
    public float LandVolume;
    public float LandHeavySpeed;
    public float Speed;
    public float RunSpeed;
    public float CrouchVolume;
    public float RunVolume;
    public float WalkVolume;
    public float NpcStepVolume;
    public float Result;
    public float Gain;
    public float Dt;
    public float PrevVy;
    public float Vy;
    public float MinStepSpeed;
    public float FootLiftMoving;
    public float FootLiftHeight;
    private int _Sprinting; public bool Sprinting {get=>_Sprinting!=0;set=>_Sprinting=value?1:0;}
    private int _Crouched; public bool Crouched {get=>_Crouched!=0;set=>_Crouched=value?1:0;}
    private int _Grounded; public bool Grounded {get=>_Grounded!=0;set=>_Grounded=value?1:0;}
    private int _PrevGrounded; public bool PrevGrounded {get=>_PrevGrounded!=0;set=>_PrevGrounded=value?1:0;}
    private int _Jumped; public bool Jumped {get=>_Jumped!=0;set=>_Jumped=value?1:0;}
    private int _HaveFootHeights; public bool HaveFootHeights {get=>_HaveFootHeights!=0;set=>_HaveFootHeights=value?1:0;}
    private int _StepsFromFeet; public bool StepsFromFeet {get=>_StepsFromFeet!=0;set=>_StepsFromFeet=value?1:0;}
    private int _Landing; public bool Landing {get=>_Landing!=0;set=>_Landing=value?1:0;}
    private int _ResetFeet; public bool ResetFeet {get=>_ResetFeet!=0;set=>_ResetFeet=value?1:0;}
    private int _ResetSteps; public bool ResetSteps {get=>_ResetSteps!=0;set=>_ResetSteps=value?1:0;}
    private int _UseFeet; public bool UseFeet {get=>_UseFeet!=0;set=>_UseFeet=value?1:0;}
    private int _UseDistance; public bool UseDistance {get=>_UseDistance!=0;set=>_UseDistance=value?1:0;}
    public int Operation;
    public int Element;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct BodyMotionFrame {
    public Vector3 Velocity;
    public Vector3 WishVelocity;
    public Vector3 Move;
    public Vector3 LastDir;
    public Vector3 StartDir;
    public Vector3 StopDir;
    public Vector3 PivotDir;
    public Vector3 StepDir;
    public float Dt;
    public float ViewYaw;
    public float Yaw;
    public float Twist;
    public float AirTime;
    public float IdleTime;
    public float MoveTime;
    public float TurnTime;
    public float TurnDone;
    public float RootYaw;
    public float StateTime;
    public float PlayerRunSpeed;
    public float PlayerSprintSpeed;
    public float RunSpeed;
    public float ClipSprint;
    public float Responsiveness;
    public float MaxPlayRate;
    public float ParamSmoothing;
    public float TurnThreshold;
    public float TurnMinTime;
    public float TurnEndAngle;
    public float TurnTimeout;
    public float TurnMoveEase;
    public float TurnLagMargin;
    public float TurnLagFloor;
    public float StopDebounce;
    public float StartIdleTime;
    public float StartMaxMove;
    public float StopMinRunTimeCrouched;
    public float StopMinRunTime;
    public float StopMinSpeedCrouched;
    public float StopMinSpeed;
    public float StopRunForward;
    public float AirborneDelay;
    public float PlayRate;
    public float TurnAngle;
    public float AccelTime;
    public float DecelTime;
    public float Random;
    public float StartGait;
    public float StopGait;
    public float PivotGait;
    public float StartTurn;
    public float StartTurnAmount;
    public float StartDistance;
    public float StopDistance;
    public float PivotDistance;
    public float PivotTravel;
    public float FidgetTime;
    public float FidgetNext;
    public float FidgetIndex;
    public float SprintRate;
    public float SprintClip;
    public float MoveDistance;
    private int _Grounded; public bool Grounded {get=>_Grounded!=0;set=>_Grounded=value?1:0;}
    private int _Crouched; public bool Crouched {get=>_Crouched!=0;set=>_Crouched=value?1:0;}
    private int _WasCrouched; public bool WasCrouched {get=>_WasCrouched!=0;set=>_WasCrouched=value?1:0;}
    private int _StartStopClips; public bool StartStopClips {get=>_StartStopClips!=0;set=>_StartStopClips=value?1:0;}
    private int _Turning; public bool Turning {get=>_Turning!=0;set=>_Turning=value?1:0;}
    private int _IsTurn; public bool IsTurn {get=>_IsTurn!=0;set=>_IsTurn=value?1:0;}
    private int _IsCrouchTurn; public bool IsCrouchTurn {get=>_IsCrouchTurn!=0;set=>_IsCrouchTurn=value?1:0;}
    private int _IsLocomotion; public bool IsLocomotion {get=>_IsLocomotion!=0;set=>_IsLocomotion=value?1:0;}
    private int _IsCrouchLoco; public bool IsCrouchLoco {get=>_IsCrouchLoco!=0;set=>_IsCrouchLoco=value?1:0;}
    private int _Jumped; public bool Jumped {get=>_Jumped!=0;set=>_Jumped=value?1:0;}
    private int _Still; public bool Still {get=>_Still!=0;set=>_Still=value?1:0;}
    private int _SetTurnAngle; public bool SetTurnAngle {get=>_SetTurnAngle!=0;set=>_SetTurnAngle=value?1:0;}
    private int _LastSprint; public bool LastSprint {get=>_LastSprint!=0;set=>_LastSprint=value?1:0;}
    private int _Moving; public bool Moving {get=>_Moving!=0;set=>_Moving=value?1:0;}
    private int _Sprint; public bool Sprint {get=>_Sprint!=0;set=>_Sprint=value?1:0;}
    private int _Airborne; public bool Airborne {get=>_Airborne!=0;set=>_Airborne=value?1:0;}
    private int _Armed; public bool Armed {get=>_Armed!=0;set=>_Armed=value?1:0;}
    private int _Busy; public bool Busy {get=>_Busy!=0;set=>_Busy=value?1:0;}
    private int _IsStart; public bool IsStart {get=>_IsStart!=0;set=>_IsStart=value?1:0;}
    private int _IsStartTurn; public bool IsStartTurn {get=>_IsStartTurn!=0;set=>_IsStartTurn=value?1:0;}
    private int _IsStop; public bool IsStop {get=>_IsStop!=0;set=>_IsStop=value?1:0;}
    private int _IsPivot; public bool IsPivot {get=>_IsPivot!=0;set=>_IsPivot=value?1:0;}
    private int _IsStep; public bool IsStep {get=>_IsStep!=0;set=>_IsStep=value?1:0;}
    private int _IsFidget; public bool IsFidget {get=>_IsFidget!=0;set=>_IsFidget=value?1:0;}
    private int _IsSprint; public bool IsSprint {get=>_IsSprint!=0;set=>_IsSprint=value?1:0;}
    private int _PivotReversed; public bool PivotReversed {get=>_PivotReversed!=0;set=>_PivotReversed=value?1:0;}
    public int Triggers;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcCallMemberFrame {
    public Vector3 Feet;
    public Vector3 Eye;
    public Vector3 GlanceAt;
    public float LastCallout;
    public float GlanceUntil;
    public float Awareness;
    public float NextChatter;
    private int _Exists; public bool Exists {get=>_Exists!=0;set=>_Exists=value?1:0;}
    private int _Dummy; public bool Dummy {get=>_Dummy!=0;set=>_Dummy=value?1:0;}
    private int _Dead; public bool Dead {get=>_Dead!=0;set=>_Dead=value?1:0;}
    private int _Fire; public bool Fire {get=>_Fire!=0;set=>_Fire=value?1:0;}
    private int _Known; public bool Known {get=>_Known!=0;set=>_Known=value?1:0;}
    private int _Reloading; public bool Reloading {get=>_Reloading!=0;set=>_Reloading=value?1:0;}
    private int _Suppress; public bool Suppress {get=>_Suppress!=0;set=>_Suppress=value?1:0;}
    private int _TriggerHeld; public bool TriggerHeld {get=>_TriggerHeld!=0;set=>_TriggerHeld=value?1:0;}
    private int _VcReloading; public bool VcReloading {get=>_VcReloading!=0;set=>_VcReloading=value?1:0;}
    private int _VcCovering; public bool VcCovering {get=>_VcCovering!=0;set=>_VcCovering=value?1:0;}
    private int _VcSuspicious; public bool VcSuspicious {get=>_VcSuspicious!=0;set=>_VcSuspicious=value?1:0;}
    public int Index;
    public int Squad;
    public int Behaviour;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcCallChannelFrame {
    public float BusyUntil;
    public float RespAt;
    public int OnAirPriority;
    private int _RespPending; public bool RespPending {get=>_RespPending!=0;set=>_RespPending=value?1:0;}
    public fixed float LastEvent[20];
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcCalloutsFrame {
    public NpcPlayerFrame Player;
    public float Now;
    private int _PlayerWasDead; public bool PlayerWasDead {get=>_PlayerWasDead!=0;set=>_PlayerWasDead=value?1:0;}
    public int Operation;
    public int Caller;
    public int Kind;
    public int Random;
    public int MemberCount;
    public int ChannelCount;
    public nint Members;
    public nint Channels;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct WardrobeRandomFrame {
    public nint Input;
    public nint Context;
    public nint Services;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcSpawnFrame {
    public Vector3 Position;
    public Vector3 Feet;
    public Vector3 Eye;
    public Vector3 LookPoint;
    public float Now;
    public float Yaw;
    public float AimYaw;
    public float NextLook;
    public float NextThink;
    public float Radius;
    public float StandCylinder;
    public float AgentRadius;
    public float AgentHeight;
    public float JogSpeed;
    public float RunSpeed;
    public int Index;
    public int Weapon;
    public int Random;
    public int Count;
    public nint Members;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcLifeFrame {
    public NpcIntentFrame Intent;
    public NpcMemoryFrame Memory;
    public Vector3 Feet;
    public Vector3 Eye;
    public Vector3 Want;
    public Vector3 Velocity;
    public Vector3 Push;
    public Vector3 Displacement;
    public Vector3 Origin;
    public Vector3 End;
    public float Now;
    public float Dt;
    public float WoundedAt;
    public float DiedAt;
    public float BleedOutTime;
    public float CorpseTime;
    public float CrawlSpeed;
    public float LimpScale;
    public float LimpUntil;
    public float StaggerUntil;
    public float Speed;
    public float Gravity;
    public float FallSpeed;
    public float BlockedTime;
    public float MeleeAt;
    public float MeleeTime;
    public float PlayerDistance;
    public float FootIKRange;
    public float StandCylinder;
    public float CrouchCylinder;
    public float Suppression;
    public float CowerUntil;
    public float Skill;
    public float Morale;
    private int _Dead; public bool Dead {get=>_Dead!=0;set=>_Dead=value?1:0;}
    private int _Wounded; public bool Wounded {get=>_Wounded!=0;set=>_Wounded=value?1:0;}
    private int _Kill; public bool Kill {get=>_Kill!=0;set=>_Kill=value?1:0;}
    private int _Despawn; public bool Despawn {get=>_Despawn!=0;set=>_Despawn=value?1:0;}
    private int _Crouch; public bool Crouch {get=>_Crouch!=0;set=>_Crouch=value?1:0;}
    private int _Aim; public bool Aim {get=>_Aim!=0;set=>_Aim=value?1:0;}
    private int _Sprint; public bool Sprint {get=>_Sprint!=0;set=>_Sprint=value?1:0;}
    private int _FootIK; public bool FootIK {get=>_FootIK!=0;set=>_FootIK=value?1:0;}
    private int _FootIKEverywhere; public bool FootIKEverywhere {get=>_FootIKEverywhere!=0;set=>_FootIKEverywhere=value?1:0;}
    private int _OnScreen; public bool OnScreen {get=>_OnScreen!=0;set=>_OnScreen=value?1:0;}
    private int _Grounded; public bool Grounded {get=>_Grounded!=0;set=>_Grounded=value?1:0;}
    private int _CallManDown; public bool CallManDown {get=>_CallManDown!=0;set=>_CallManDown=value?1:0;}
    public int Operation;
    public nint Services;
    public nint Context;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcPlayerNoiseFrame {
    public NpcPlayerFrame Player;
    public NpcNoiseFrame Gun;
    public NpcNoiseFrame Step;
    public NpcNoiseFrame Reload;
    public Vector3 Post;
    public float Now;
    public float Dt;
    public float FootstepTimer;
    public float Still;
    public int Count;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcRespawnPointFrame {
    public Vector3 Position;
    private int _Seen; public bool Seen {get=>_Seen!=0;set=>_Seen=value?1:0;}
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcRespawnFrame {
    public NpcPlayerFrame Player;
    public float Now;
    public float Timer;
    public int Alive;
    public int Wanted;
    public int Count;
    public int Best;
    private int _Ready; public bool Ready {get=>_Ready!=0;set=>_Ready=value?1:0;}
    private int _Discard; public bool Discard {get=>_Discard!=0;set=>_Discard=value?1:0;}
    public nint Points;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcShotPoseFrame {
    public NpcPlayerFrame Player;
    public NpcIntentFrame Intent;
    public NpcMemoryFrame Memory;
    public Vector3 Feet;
    public Vector3 Eye;
    public Vector3 Velocity;
    public Vector3 SeenPoint;
    public Vector3 BlindOffset;
    public Vector3 CoverPosition;
    public Vector3 Peek;
    public Vector3 CameraOffset;
    public Vector3 Shot;
    public float Now;
    public float Dt;
    public float AimYaw;
    public float AimPitch;
    public float BlindLift;
    public float MeleeAt;
    public float MeleeTime;
    public float TimeOnTarget;
    public float Suppression;
    public float Skill;
    public float Difficulty;
    public float LastHurt;
    public float Roll;
    private int _Alive; public bool Alive {get=>_Alive!=0;set=>_Alive=value?1:0;}
    private int _HighCover; public bool HighCover {get=>_HighCover!=0;set=>_HighCover=value?1:0;}
    private int _TriggerHeld; public bool TriggerHeld {get=>_TriggerHeld!=0;set=>_TriggerHeld=value?1:0;}
    private int _FirstShot; public bool FirstShot {get=>_FirstShot!=0;set=>_FirstShot=value?1:0;}
    private int _Wounded; public bool Wounded {get=>_Wounded!=0;set=>_Wounded=value?1:0;}
    private int _HaveShot; public bool HaveShot {get=>_HaveShot!=0;set=>_HaveShot=value?1:0;}
    public int VisiblePoints;
    public int Weapon;
    public nint Services;
    public nint Context;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct DevFrame {
    private int _Open; public bool Open {get=>_Open!=0;set=>_Open=value?1:0;}
    private int _InfiniteAmmo; public bool InfiniteAmmo {get=>_InfiniteAmmo!=0;set=>_InfiniteAmmo=value?1:0;}
    private int _Invisible; public bool Invisible {get=>_Invisible!=0;set=>_Invisible=value?1:0;}
    private int _AiOverlay; public bool AiOverlay {get=>_AiOverlay!=0;set=>_AiOverlay=value?1:0;}
    private int _God; public bool God {get=>_God!=0;set=>_God=value?1:0;}
    private int _Frozen; public bool Frozen {get=>_Frozen!=0;set=>_Frozen=value?1:0;}
    private int _HoldFire; public bool HoldFire {get=>_HoldFire!=0;set=>_HoldFire=value?1:0;}
    private int _HaveBloodLab; public bool HaveBloodLab {get=>_HaveBloodLab!=0;set=>_HaveBloodLab=value?1:0;}
    private int _BloodLab; public bool BloodLab {get=>_BloodLab!=0;set=>_BloodLab=value?1:0;}
    public float Difficulty;
    public float TimeScale;
    public int Operation;
    public int Count;
    public int Alive;
    public int Known;
    public int Wanted;
    public int Spawns;
    public int Result;
    public nint Members;
    public nint Services;
    public nint Context;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct GameSessionFrame {
    private int _HasInput; public bool HasInput {get=>_HasInput!=0;set=>_HasInput=value?1:0;}
    private int _GravityLive; public bool GravityLive {get=>_GravityLive!=0;set=>_GravityLive=value?1:0;}
    private int _Dead; public bool Dead {get=>_Dead!=0;set=>_Dead=value?1:0;}
    private int _Equipped; public bool Equipped {get=>_Equipped!=0;set=>_Equipped=value?1:0;}
    private int _FirePressed; public bool FirePressed {get=>_FirePressed!=0;set=>_FirePressed=value?1:0;}
    private int _FireHeld; public bool FireHeld {get=>_FireHeld!=0;set=>_FireHeld=value?1:0;}
    private int _ReloadHeld; public bool ReloadHeld {get=>_ReloadHeld!=0;set=>_ReloadHeld=value?1:0;}
    private int _Invisible; public bool Invisible {get=>_Invisible!=0;set=>_Invisible=value?1:0;}
    private int _InfiniteAmmo; public bool InfiniteAmmo {get=>_InfiniteAmmo!=0;set=>_InfiniteAmmo=value?1:0;}
    private int _PlayerValid; public bool PlayerValid {get=>_PlayerValid!=0;set=>_PlayerValid=value?1:0;}
    private int _Armed; public bool Armed {get=>_Armed!=0;set=>_Armed=value?1:0;}
    private int _JustDied; public bool JustDied {get=>_JustDied!=0;set=>_JustDied=value?1:0;}
    private int _WantsRespawn; public bool WantsRespawn {get=>_WantsRespawn!=0;set=>_WantsRespawn=value?1:0;}
    private int _NpcHit; public bool NpcHit {get=>_NpcHit!=0;set=>_NpcHit=value?1:0;}
    private int _AliveHit; public bool AliveHit {get=>_AliveHit!=0;set=>_AliveHit=value?1:0;}
    private int _Killed; public bool Killed {get=>_Killed!=0;set=>_Killed=value?1:0;}
    private int _Head; public bool Head {get=>_Head!=0;set=>_Head=value?1:0;}
    private int _AimHeld; public bool AimHeld {get=>_AimHeld!=0;set=>_AimHeld=value?1:0;}
    private int _SprintHeld; public bool SprintHeld {get=>_SprintHeld!=0;set=>_SprintHeld=value?1:0;}
    public Vector3 Position;
    public Vector3 Velocity;
    public Vector3 Camera;
    public Vector3 RespawnFeet;
    public float Scroll;
    public float EyeHeight;
    public int Operation;
    public int Commands;
    public int SlotDirection;
    public int Ammo;
    public int Magazine;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct NpcShotEffectFrame {
    public NpcPlayerFrame Player;
    public Vector3 Origin;
    public Vector3 End;
    public Vector3 Eye;
    public Vector3 Closest;
    public Vector3 ReloadPosition;
    public Vector3 PumpPosition;
    public float Reach;
    public float Miss;
    public float Suppression;
    public float Damage;
    public float DamageScale;
    private int _FirstPellet; public bool FirstPellet {get=>_FirstPellet!=0;set=>_FirstPellet=value?1:0;}
    private int _Shotgun; public bool Shotgun {get=>_Shotgun!=0;set=>_Shotgun=value?1:0;}
    private int _HitPlayer; public bool HitPlayer {get=>_HitPlayer!=0;set=>_HitPlayer=value?1:0;}
    private int _Reloading; public bool Reloading {get=>_Reloading!=0;set=>_Reloading=value?1:0;}
    private int _Pumping; public bool Pumping {get=>_Pumping!=0;set=>_Pumping=value?1:0;}
    private int _WasReloading; public bool WasReloading {get=>_WasReloading!=0;set=>_WasReloading=value?1:0;}
    private int _WasPumping; public bool WasPumping {get=>_WasPumping!=0;set=>_WasPumping=value?1:0;}
    private int _Friendly; public bool Friendly {get=>_Friendly!=0;set=>_Friendly=value?1:0;}
    public int Operation;
    public int Commands;
    public int Tracer;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct ImpactFrame {
    public double Now;
    public double Last;
    public double Interval;
    public float Speed;
    public float MinSpeed;
    public float FullSpeed;
    public float Volume;
    public float GainMin;
    public float Gain;
    public float Radius;
    public float ShellRadius;
    public float Miss;
    public float FlybyRadius;
    public float FlybyVolume;
    public float FarGain;
    private int _Enabled; public bool Enabled {get=>_Enabled!=0;set=>_Enabled=value?1:0;}
    private int _CasingsEnabled; public bool CasingsEnabled {get=>_CasingsEnabled!=0;set=>_CasingsEnabled=value?1:0;}
    public int Operation;
    public int Contact;
    public int MaxContacts;
    public int Result;
}
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct WeaponLoadoutFrame {
    private int _Active; public bool Active {get=>_Active!=0;set=>_Active=value?1:0;}
    private int _Equipped; public bool Equipped {get=>_Equipped!=0;set=>_Equipped=value?1:0;}
    private int _Requested; public bool Requested {get=>_Requested!=0;set=>_Requested=value?1:0;}
    private int _Chambered; public bool Chambered {get=>_Chambered!=0;set=>_Chambered=value?1:0;}
    private int _Hidden; public bool Hidden {get=>_Hidden!=0;set=>_Hidden=value?1:0;}
    private int _InTransition; public bool InTransition {get=>_InTransition!=0;set=>_InTransition=value?1:0;}
    public float CycleWait;
    public int Operation;
    public int Value;
    public int Count;
    public int Slot;
    public int Pending;
    public int Ammo;
    public int Magazine;
    public int Burst;
    public int Commands;
    public nint SlotAmmo;
}
