// Generated by tools/generate_script_abi.py. Do not edit.
#pragma once
#include <cstdint>
namespace Scripting {
constexpr int kVersion = 2;
struct Vec3 { float x=0, y=0, z=0; };
struct ProjectCall {
    const char* Operation{};
    void* Data{};
    std::int32_t Size{};
};
struct EntityFrame {
    float Dt{};
    std::uint32_t Entity{};
    std::uint32_t Script{};
    std::int32_t Phase{};
    std::int32_t Enabled{};
    const char* ClassName{};
    const char* Fields{};
};
struct NativeRequest {
    Vec3 A{};
    Vec3 B{};
    Vec3 C{};
    float Value{};
    std::uint32_t Entity{};
    std::uint32_t Script{};
    std::int32_t Result{};
    const char* Text{};
};
using NativeCall = int (*)(int, NativeRequest*);
}
