"""Shared build plumbing: loudness finishing, wav + manifest output."""
import json
import os

import numpy as np

import adsp

HERE = os.path.dirname(os.path.abspath(__file__))
AUDIO_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "project", "assets", "Audio"))
MANIFEST = os.path.join(AUDIO_DIR, "audio_manifest.json")
TARGETS = json.load(open(os.path.join(HERE, "recipes", "targets.json")))


def finish(x, layer, ceiling_db=None, max_gr_db=7.0, trim_edges=True, target=None, loop=False):
    """Bring a rendered one-shot to its layer's loudness target without breaking the peak ceiling.

    Gain to target; if that pushes the true peak over the ceiling, a limiter takes up to max_gr_db of it (the sound
    gets denser, not just quieter) and the rest is plain gain reduction."""
    ceiling = TARGETS["peak_dbtp_max"] if ceiling_db is None else ceiling_db
    tgt = TARGETS["layers"][layer]["target"] if target is None else target
    if not loop:                                       # a loop keeps its (circularly continuous) edges untouched
        x = adsp.remove_dc(x)
    if trim_edges and not loop:                        # guarantee a click-free start and end
        x = adsp.fade(x, int(0.0008 * adsp.SR), int(0.004 * adsp.SR))
    _, m = adsp.lufs(x)
    g0 = tgt - m
    g = g0
    y = adsp.gain_db(x, g)
    for _ in range(6):                                  # limiter-aware loudness loop: measure what we actually ship
        y = adsp.limit(adsp.gain_db(x, g), ceiling) if adsp.true_peak_db(adsp.gain_db(x, g)) > ceiling \
            else adsp.gain_db(x, g)
        err = tgt - adsp.lufs(y)[1]
        if abs(err) < 0.2:
            break
        g = min(g + err, g0 + max_gr_db)                # never let the limiter do more than max_gr_db of the work
    return y.astype(np.float32)


def measure(x):
    li, lm = adsp.lufs(x)
    return {"lufs_i": round(li, 2), "lufs_m_max": round(lm, 2),
            "true_peak_dbtp": round(adsp.true_peak_db(x), 2), "length_s": round(len(x) / adsp.SR, 3),
            "peak_ms": round(float(np.argmax(np.abs(x).max(axis=1))) * 1000.0 / adsp.SR, 1)}


def emit(rel_path, x, key, layer, extra=None, mono=False):
    """Write project/assets/Audio/<rel_path> and return its manifest entry."""
    path = os.path.join(AUDIO_DIR, rel_path)
    y = adsp.to_mono(x)[:, None].repeat(2, axis=1).astype(np.float32) if mono else x
    seed = sum(map(ord, rel_path))                     # stable dither seed per file (hash() is salted per run)
    adsp.write_wav(path, y, mono=mono, dither_seed=seed)
    entry = {"file": rel_path.replace("\\", "/"), "key": key, "layer": layer, "channels": 1 if mono else 2,
             "sample_rate": adsp.SR}
    entry.update(measure(y))
    entry["anchor_ms"] = round(adsp.anchor_ms(y), 1)       # contact transient inside the file (see docs/AUDIO.md)
    if extra:
        entry.update(extra)
    return entry


def update_manifest(entries, owner_prefixes):
    """Replace every manifest entry whose file starts with one of owner_prefixes by `entries`; keep the rest."""
    old = []
    if os.path.exists(MANIFEST):
        old = json.load(open(MANIFEST)).get("files", [])
    keep = [e for e in old if not any(e["file"].startswith(p) for p in owner_prefixes)]
    files = sorted(keep + entries, key=lambda e: e["file"])
    doc = {"_doc": "Generated by tools/audio/*.py -- do not hand edit. file is relative to project/assets/Audio. "
                   "key = engine event key (variants share one key; pick randomly, avoid immediate repeats). "
                   "lufs_m_max = loudest 400 ms momentary window (BS.1770), true_peak_dbtp = 4x oversampled.",
           "sample_rate": adsp.SR, "files": files}
    os.makedirs(AUDIO_DIR, exist_ok=True)
    with open(MANIFEST, "w") as fh:
        json.dump(doc, fh, indent=1)
    return len(files)
