#!/usr/bin/env python3
"""Generates src/Editor/Enhancers/FAIconTable.inc from extern/IconsFontAwesome6.h.

The Editor Enhancers (row/folder styles, the icon picker, favorites) store icons by their Font
Awesome *name* ("cube", "folder-open") rather than by codepoint, so a style written today still
resolves after the bundled header is regenerated for a newer FA release. This table is the
name -> UTF-8 lookup those features use. It is sorted by name so the C++ side can binary-search it.

The output is checked in (no build-time Python dependency); rerun this after updating the header:

    python tools/gen_fa_icon_table.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "extern" / "IconsFontAwesome6.h"
OUT = ROOT / "src" / "Editor" / "Enhancers" / "FAIconTable.inc"

DEFINE_RE = re.compile(r'^#define ICON_FA_([A-Z0-9_]+) "((?:[^"\\]|\\.)*)"')


def main() -> int:
    entries = {}
    for line in HEADER.read_text(encoding="utf-8").splitlines():
        m = DEFINE_RE.match(line)
        if not m:
            continue
        name = m.group(1).lower().replace("_", "-")
        entries[name] = m.group(2)

    lines = [
        "// GENERATED by tools/gen_fa_icon_table.py from extern/IconsFontAwesome6.h - do not edit.",
        "// One TARTARUS_FA_ICON(name, utf8) row per icon, sorted by name (binary-searched).",
    ]
    for name in sorted(entries):
        lines.append(f'TARTARUS_FA_ICON("{name}", "{entries[name]}")')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(entries)} icons to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
