"""Generate the blittable C++/C# scripting ABI. Run after changing the schema."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schema = {'ProjectCall': {'ptr': 'Operation', 'data': 'Data', 'int': 'Size'},
 'EntityFrame': {'float': 'Dt',
                 'uint': 'Entity Script',
                 'int': 'Phase Enabled',
                 'ptr': 'ClassName Fields'},
 'NativeRequest': {'Vec3': 'A B C',
                   'float': 'Value',
                   'uint': 'Entity Script',
                   'int': 'Result',
                   'ptr': 'Text'}}
cpp = ['// Generated by tools/generate_script_abi.py. Do not edit.', '#pragma once', '#include <cstdint>', 'namespace Scripting {', 'constexpr int kVersion = 3;', 'struct Vec3 { float x=0, y=0, z=0; };']
cs = ['// Generated by tools/generate_script_abi.py. Do not edit.', 'using System.Numerics;', 'using System.Runtime.InteropServices;', 'namespace Tartarus;', 'public static class ScriptAbi { public const int Version = 3; }']
for name, groups in schema.items():
    cpp.append(f'struct {name} {{')
    cs.extend(['[StructLayout(LayoutKind.Sequential)]', f'public struct {name} {{'])
    for kind, names in groups.items():
        for field in names.split():
            cpp.append(f'    {dict(float="float", int="std::int32_t", uint="std::uint32_t", Vec3="Vec3", ptr="const char*", data="void*")[kind]} {field}{{}};')
            cs.append(f'    public {dict(float="float", int="int", uint="uint", Vec3="Vector3", ptr="nint", data="nint")[kind]} {field};')
    cpp.append('};')
    cs.append('}')
cpp += ['using NativeCall = int (*)(int, NativeRequest*);', '}']
(root/'src/Game/Scripting').mkdir(parents=True, exist_ok=True)
(root/'managed/Tartarus.Runtime').mkdir(parents=True, exist_ok=True)
(root/'src/Game/Scripting/ScriptAbi.h').write_text('\n'.join(cpp)+'\n')
(root/'managed/Tartarus.Runtime/ScriptAbi.cs').write_text('\n'.join(cs)+'\n')
