"""Generate the blittable C++/C# scripting ABI. Run after changing the schema."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schema = {
    'PlayerFrame': {
        'float': 'Dt Yaw Pitch MoveX MoveY LookPitch LookYaw SizeX SizeY EyeHeight MoveSpeed SprintMultiplier JumpSpeed Gravity MouseSensitivity StickLookDegPerSec KillY RootMotionWeight MaxYawRate YawFreeCenter YawFreeRange CrouchHeight CrouchSpeedMultiplier JumpBufferTime CoyoteTime GroundAccelTime GroundDecelTime AirAccelTime SinceGrounded JumpBuffer CrouchBlend YawDropped',
        'Vec3': 'Position Velocity RespawnFeet RootMotionVelocity WishVelocity',
        'int': 'ReadInput Sprint JumpDown Crouch AimHeld Grounded Crouched Jumped',
    },
    'WeaponFrame': {
        'float': 'Dt Rpm CycleDelay HoldSeconds RegripMin RegripMax Cooldown CycleWait IdleTime RegripDelay SinceShot SinceUnhidden ReloadHeldSeconds Random',
        'int': 'Operation Ammo Magazine BurstRounds AllowFullAuto PerRound CycleAfterShot HipProcedural RecoilProfile UnityRecoil Equipped Chambered CycleSeen StopReload FullAuto BurstRemaining WaitingShot Tags InTransition WallBlocked Pressed Held ReloadWasDown ReloadHoldFired Events Commands Result',
    },
    'EntityFrame': {
        'float': 'Dt', 'uint': 'Entity Script', 'int': 'Phase Enabled', 'ptr': 'ClassName Fields'
    },
    'ShotFrame': {
        'Vec3': 'Origin Direction',
        'float': 'Spread ImpactImpulse ImpactMaxSpeed BulletHoleRadius Range',
        'int': 'Pellets RandomSeed',
    },
    'NativeRequest': {
        'Vec3': 'A B C', 'float': 'Value', 'uint': 'Entity Script', 'int': 'Result', 'ptr': 'Text'
    },
}
cpp = ['// Generated by tools/generate_script_abi.py. Do not edit.', '#pragma once', '#include <cstdint>', 'namespace Scripting {', 'constexpr int kVersion = 2;', 'struct Vec3 { float x=0, y=0, z=0; };']
cs = ['// Generated by tools/generate_script_abi.py. Do not edit.', 'using System.Numerics;', 'using System.Runtime.InteropServices;', 'namespace Tartarus;', 'public static class ScriptAbi { public const int Version = 2; }']
for name, groups in schema.items():
    cpp.append(f'struct {name} {{')
    cs.extend(['[StructLayout(LayoutKind.Sequential)]', f'public struct {name} {{'])
    for kind, names in groups.items():
        for field in names.split():
            cpp.append(f'    {dict(float="float", int="std::int32_t", uint="std::uint32_t", Vec3="Vec3", ptr="const char*")[kind]} {field}{{}};')
            cs.append(f'    public {dict(float="float", int="int", uint="uint", Vec3="Vector3", ptr="nint")[kind]} {field};')
    cpp.append('};')
    cs.append('}')
cpp += ['using NativeCall = int (*)(int, NativeRequest*);', '}']
(root/'src/Game/Scripting').mkdir(parents=True, exist_ok=True)
(root/'managed/Tartarus.Runtime').mkdir(parents=True, exist_ok=True)
(root/'src/Game/Scripting/ScriptAbi.h').write_text('\n'.join(cpp)+'\n')
(root/'managed/Tartarus.Runtime/ScriptAbi.cs').write_text('\n'.join(cs)+'\n')
